//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobPostingService.IJobApplication")]
    public interface IJobApplication {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IJobApplication/InterviewCandidate")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InterviewCandidate(string ApplicationId, bool PassedInterview);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IJobApplication/InterviewCandidate")]
        System.Threading.Tasks.Task InterviewCandidateAsync(string ApplicationId, bool PassedInterview);
        
        // CODEGEN: Parameter 'application' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobApplication/ApplyForJob", ReplyAction="http://tempuri.org/IJobApplication/ApplyForJobResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="applicationId")]
        PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobResponse ApplyForJob(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobApplication/ApplyForJob", ReplyAction="http://tempuri.org/IJobApplication/ApplyForJobResponse")]
        System.Threading.Tasks.Task<PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobResponse> ApplyForJobAsync(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobRequest request);
        
        // CODEGEN: Generating message contract since the operation TerminateJobApplication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IJobApplication/TerminateJobApplication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void TerminateJobApplication(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.TerminateJobApplication request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IJobApplication/TerminateJobApplication")]
        System.Threading.Tasks.Task TerminateJobApplicationAsync(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.TerminateJobApplication request);
        
        // CODEGEN: Generating message contract since the operation GetJobApplicationStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobApplication/GetJobApplicationStatus", ReplyAction="http://tempuri.org/IJobApplication/GetJobApplicationStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusResponse1 GetJobApplicationStatus(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobApplication/GetJobApplicationStatus", ReplyAction="http://tempuri.org/IJobApplication/GetJobApplicationStatusResponse")]
        System.Threading.Tasks.Task<PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusResponse1> GetJobApplicationStatusAsync(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Exercise1.Core")]
    public partial class JobApplication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Candidate applyingCandidateField;
        
        private int jobPostingIdField;
        
        private bool jobPostingIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Candidate ApplyingCandidate {
            get {
                return this.applyingCandidateField;
            }
            set {
                this.applyingCandidateField = value;
                this.RaisePropertyChanged("ApplyingCandidate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int JobPostingId {
            get {
                return this.jobPostingIdField;
            }
            set {
                this.jobPostingIdField = value;
                this.RaisePropertyChanged("JobPostingId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobPostingIdSpecified {
            get {
                return this.jobPostingIdFieldSpecified;
            }
            set {
                this.jobPostingIdFieldSpecified = value;
                this.RaisePropertyChanged("JobPostingIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Exercise1.Core")]
    public partial class Candidate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int candidateIdField;
        
        private bool candidateIdFieldSpecified;
        
        private string emailAddressField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string sSNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CandidateId {
            get {
                return this.candidateIdField;
            }
            set {
                this.candidateIdField = value;
                this.RaisePropertyChanged("CandidateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CandidateIdSpecified {
            get {
                return this.candidateIdFieldSpecified;
            }
            set {
                this.candidateIdFieldSpecified = value;
                this.RaisePropertyChanged("CandidateIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
                this.RaisePropertyChanged("SSN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Exercise1.Core")]
    public partial class ContactManager : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailAddressField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private int managerIdField;
        
        private bool managerIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ManagerId {
            get {
                return this.managerIdField;
            }
            set {
                this.managerIdField = value;
                this.RaisePropertyChanged("ManagerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ManagerIdSpecified {
            get {
                return this.managerIdFieldSpecified;
            }
            set {
                this.managerIdFieldSpecified = value;
                this.RaisePropertyChanged("ManagerIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Exercise1.Core")]
    public partial class JobPosting : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ContactManager hiringManagerField;
        
        private int jobPostingIdField;
        
        private bool jobPostingIdFieldSpecified;
        
        private string positionNameField;
        
        private System.DateTime postingDateField;
        
        private bool postingDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public ContactManager HiringManager {
            get {
                return this.hiringManagerField;
            }
            set {
                this.hiringManagerField = value;
                this.RaisePropertyChanged("HiringManager");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int JobPostingId {
            get {
                return this.jobPostingIdField;
            }
            set {
                this.jobPostingIdField = value;
                this.RaisePropertyChanged("JobPostingId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobPostingIdSpecified {
            get {
                return this.jobPostingIdFieldSpecified;
            }
            set {
                this.jobPostingIdFieldSpecified = value;
                this.RaisePropertyChanged("JobPostingIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string PositionName {
            get {
                return this.positionNameField;
            }
            set {
                this.positionNameField = value;
                this.RaisePropertyChanged("PositionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
                this.RaisePropertyChanged("PostingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostingDateSpecified {
            get {
                return this.postingDateFieldSpecified;
            }
            set {
                this.postingDateFieldSpecified = value;
                this.RaisePropertyChanged("PostingDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Exercise1.Core")]
    public partial class JobApplicationStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jobApplicationIdField;
        
        private JobPosting jobAppliedToField;
        
        private bool passedBackgroundCheckField;
        
        private bool passedBackgroundCheckFieldSpecified;
        
        private bool passedInterviewField;
        
        private bool passedInterviewFieldSpecified;
        
        private JobApplication submittedApplicationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string JobApplicationId {
            get {
                return this.jobApplicationIdField;
            }
            set {
                this.jobApplicationIdField = value;
                this.RaisePropertyChanged("JobApplicationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public JobPosting JobAppliedTo {
            get {
                return this.jobAppliedToField;
            }
            set {
                this.jobAppliedToField = value;
                this.RaisePropertyChanged("JobAppliedTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool PassedBackgroundCheck {
            get {
                return this.passedBackgroundCheckField;
            }
            set {
                this.passedBackgroundCheckField = value;
                this.RaisePropertyChanged("PassedBackgroundCheck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PassedBackgroundCheckSpecified {
            get {
                return this.passedBackgroundCheckFieldSpecified;
            }
            set {
                this.passedBackgroundCheckFieldSpecified = value;
                this.RaisePropertyChanged("PassedBackgroundCheckSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool PassedInterview {
            get {
                return this.passedInterviewField;
            }
            set {
                this.passedInterviewField = value;
                this.RaisePropertyChanged("PassedInterview");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PassedInterviewSpecified {
            get {
                return this.passedInterviewFieldSpecified;
            }
            set {
                this.passedInterviewFieldSpecified = value;
                this.RaisePropertyChanged("PassedInterviewSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public JobApplication SubmittedApplication {
            get {
                return this.submittedApplicationField;
            }
            set {
                this.submittedApplicationField = value;
                this.RaisePropertyChanged("SubmittedApplication");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyForJob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ApplyForJobRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.JobApplication application;
        
        public ApplyForJobRequest() {
        }
        
        public ApplyForJobRequest(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.JobApplication application) {
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyForJobResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ApplyForJobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string applicationId;
        
        public ApplyForJobResponse() {
        }
        
        public ApplyForJobResponse(string applicationId) {
            this.applicationId = applicationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateJobApplication {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        public TerminateJobApplication() {
        }
        
        public TerminateJobApplication(string guid) {
            this.guid = guid;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetJobApplicationStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private JobApplicationStatus currentJobApplicationStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public JobApplicationStatus CurrentJobApplicationStatus {
            get {
                return this.currentJobApplicationStatusField;
            }
            set {
                this.currentJobApplicationStatusField = value;
                this.RaisePropertyChanged("CurrentJobApplicationStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJobApplicationStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        public GetJobApplicationStatusRequest() {
        }
        
        public GetJobApplicationStatusRequest(string guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJobApplicationStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusResponse GetJobApplicationStatusResponse;
        
        public GetJobApplicationStatusResponse1() {
        }
        
        public GetJobApplicationStatusResponse1(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusResponse GetJobApplicationStatusResponse) {
            this.GetJobApplicationStatusResponse = GetJobApplicationStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobApplicationChannel : PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobApplicationClient : System.ServiceModel.ClientBase<PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication>, PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication {
        
        public JobApplicationClient() {
        }
        
        public JobApplicationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobApplicationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobApplicationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InterviewCandidate(string ApplicationId, bool PassedInterview) {
            base.Channel.InterviewCandidate(ApplicationId, PassedInterview);
        }
        
        public System.Threading.Tasks.Task InterviewCandidateAsync(string ApplicationId, bool PassedInterview) {
            return base.Channel.InterviewCandidateAsync(ApplicationId, PassedInterview);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobResponse PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication.ApplyForJob(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobRequest request) {
            return base.Channel.ApplyForJob(request);
        }
        
        public string ApplyForJob(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.JobApplication application) {
            PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobRequest inValue = new PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobRequest();
            inValue.application = application;
            PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobResponse retVal = ((PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication)(this)).ApplyForJob(inValue);
            return retVal.applicationId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobResponse> PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication.ApplyForJobAsync(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobRequest request) {
            return base.Channel.ApplyForJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobResponse> ApplyForJobAsync(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.JobApplication application) {
            PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobRequest inValue = new PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.ApplyForJobRequest();
            inValue.application = application;
            return ((PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication)(this)).ApplyForJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication.TerminateJobApplication(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.TerminateJobApplication request) {
            base.Channel.TerminateJobApplication(request);
        }
        
        public void TerminateJobApplication(string guid) {
            PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.TerminateJobApplication inValue = new PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.TerminateJobApplication();
            inValue.guid = guid;
            ((PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication)(this)).TerminateJobApplication(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication.TerminateJobApplicationAsync(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.TerminateJobApplication request) {
            return base.Channel.TerminateJobApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task TerminateJobApplicationAsync(string guid) {
            PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.TerminateJobApplication inValue = new PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.TerminateJobApplication();
            inValue.guid = guid;
            return ((PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication)(this)).TerminateJobApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusResponse1 PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication.GetJobApplicationStatus(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusRequest request) {
            return base.Channel.GetJobApplicationStatus(request);
        }
        
        public PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusResponse GetJobApplicationStatus(string guid) {
            PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusRequest inValue = new PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusRequest();
            inValue.guid = guid;
            PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusResponse1 retVal = ((PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication)(this)).GetJobApplicationStatus(inValue);
            return retVal.GetJobApplicationStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusResponse1> PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication.GetJobApplicationStatusAsync(PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusRequest request) {
            return base.Channel.GetJobApplicationStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusResponse1> GetJobApplicationStatusAsync(string guid) {
            PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusRequest inValue = new PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.GetJobApplicationStatusRequest();
            inValue.guid = guid;
            return ((PROWF45.CH11.WCF.WORKFLOW.CLIENT.SERVICE.JobPostingService.IJobApplication)(this)).GetJobApplicationStatusAsync(inValue);
        }
    }
}
