//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claims.Web.ProcessClaim.WF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcessClaim.WF.IProcessClaimService")]
    public interface IProcessClaimService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessClaimService/ProcessClaim", ReplyAction="http://tempuri.org/IProcessClaimService/ProcessClaimResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnStatus")]
        bool ProcessClaim(BusinessEntities.Claim claim);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcessClaimServiceChannel : Claims.Web.ProcessClaim.WF.IProcessClaimService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessClaimServiceClient : System.ServiceModel.ClientBase<Claims.Web.ProcessClaim.WF.IProcessClaimService>, Claims.Web.ProcessClaim.WF.IProcessClaimService {
        
        public ProcessClaimServiceClient() {
        }
        
        public ProcessClaimServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessClaimServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessClaimServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessClaimServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ProcessClaim(BusinessEntities.Claim claim) {
            return base.Channel.ProcessClaim(claim);
        }
    }
}
