//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claims.Web.Appraisal.WCF.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Appraisal.WCF.Proxy.AppraisalService")]
    public interface AppraisalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppraisalService/FindAllClaims", ReplyAction="http://tempuri.org/AppraisalService/FindAllClaimsResponse")]
        System.Collections.Generic.List<BusinessEntities.Claim> FindAllClaims();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppraisalService/FindPendingClaims", ReplyAction="http://tempuri.org/AppraisalService/FindPendingClaimsResponse")]
        System.Collections.Generic.List<BusinessEntities.Claim> FindPendingClaims();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppraisalService/GetLastClaim", ReplyAction="http://tempuri.org/AppraisalService/GetLastClaimResponse")]
        BusinessEntities.Claim GetLastClaim();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppraisalService/GetClaim", ReplyAction="http://tempuri.org/AppraisalService/GetClaimResponse")]
        BusinessEntities.Claim GetClaim(int claimId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppraisalService/Save", ReplyAction="http://tempuri.org/AppraisalService/SaveResponse")]
        void Save(BusinessEntities.Claim claim);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AppraisalServiceChannel : Claims.Web.Appraisal.WCF.Proxy.AppraisalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppraisalServiceClient : System.ServiceModel.ClientBase<Claims.Web.Appraisal.WCF.Proxy.AppraisalService>, Claims.Web.Appraisal.WCF.Proxy.AppraisalService {
        
        public AppraisalServiceClient() {
        }
        
        public AppraisalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppraisalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppraisalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppraisalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BusinessEntities.Claim> FindAllClaims() {
            return base.Channel.FindAllClaims();
        }
        
        public System.Collections.Generic.List<BusinessEntities.Claim> FindPendingClaims() {
            return base.Channel.FindPendingClaims();
        }
        
        public BusinessEntities.Claim GetLastClaim() {
            return base.Channel.GetLastClaim();
        }
        
        public BusinessEntities.Claim GetClaim(int claimId) {
            return base.Channel.GetClaim(claimId);
        }
        
        public void Save(BusinessEntities.Claim claim) {
            base.Channel.Save(claim);
        }
    }
}
