//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowActivities.CarRentalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarRentalService.CarRentalService")]
    public interface CarRentalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CarRentalService/FindRentalCar", ReplyAction="http://tempuri.org/CarRentalService/FindRentalCarResponse")]
        WorkflowActivities.CarRentalService.FindRentalCarResponse FindRentalCar(WorkflowActivities.CarRentalService.FindRentalCarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindRentalCar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindRentalCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int claimId;
        
        public FindRentalCarRequest() {
        }
        
        public FindRentalCarRequest(int claimId) {
            this.claimId = claimId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindRentalCarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindRentalCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FindRentalCarResult;
        
        public FindRentalCarResponse() {
        }
        
        public FindRentalCarResponse(string FindRentalCarResult) {
            this.FindRentalCarResult = FindRentalCarResult;
        }
    }
}
