//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowActivities.BillingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BillingService.BillingService")]
    public interface BillingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BillingService/ProcessClaim", ReplyAction="http://tempuri.org/BillingService/ProcessClaimResponse")]
        WorkflowActivities.BillingService.ProcessClaimResponse ProcessClaim(WorkflowActivities.BillingService.ProcessClaimRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessClaim", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessClaimRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int claimId;
        
        public ProcessClaimRequest() {
        }
        
        public ProcessClaimRequest(int claimId) {
            this.claimId = claimId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessClaimResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProcessClaimResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ProcessClaimResult;
        
        public ProcessClaimResponse() {
        }
        
        public ProcessClaimResponse(string ProcessClaimResult) {
            this.ProcessClaimResult = ProcessClaimResult;
        }
    }
}
