//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowActivities.AppraisalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppraisalService.AppraisalService")]
    public interface AppraisalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppraisalService/FindAllClaims", ReplyAction="http://tempuri.org/AppraisalService/FindAllClaimsResponse")]
        WorkflowActivities.AppraisalService.FindAllClaimsResponse FindAllClaims(WorkflowActivities.AppraisalService.FindAllClaimsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppraisalService/FindPendingClaims", ReplyAction="http://tempuri.org/AppraisalService/FindPendingClaimsResponse")]
        WorkflowActivities.AppraisalService.FindPendingClaimsResponse FindPendingClaims(WorkflowActivities.AppraisalService.FindPendingClaimsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppraisalService/GetLastClaim", ReplyAction="http://tempuri.org/AppraisalService/GetLastClaimResponse")]
        WorkflowActivities.AppraisalService.GetLastClaimResponse GetLastClaim(WorkflowActivities.AppraisalService.GetLastClaimRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppraisalService/GetClaim", ReplyAction="http://tempuri.org/AppraisalService/GetClaimResponse")]
        WorkflowActivities.AppraisalService.GetClaimResponse GetClaim(WorkflowActivities.AppraisalService.GetClaimRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppraisalService/Save", ReplyAction="http://tempuri.org/AppraisalService/SaveResponse")]
        WorkflowActivities.AppraisalService.SaveResponse Save(WorkflowActivities.AppraisalService.SaveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllClaims", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindAllClaimsRequest {
        
        public FindAllClaimsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindAllClaimsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindAllClaimsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BusinessEntities.Claim> FindAllClaimsResult;
        
        public FindAllClaimsResponse() {
        }
        
        public FindAllClaimsResponse(System.Collections.Generic.List<BusinessEntities.Claim> FindAllClaimsResult) {
            this.FindAllClaimsResult = FindAllClaimsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindPendingClaims", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindPendingClaimsRequest {
        
        public FindPendingClaimsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindPendingClaimsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindPendingClaimsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BusinessEntities.Claim> FindPendingClaimsResult;
        
        public FindPendingClaimsResponse() {
        }
        
        public FindPendingClaimsResponse(System.Collections.Generic.List<BusinessEntities.Claim> FindPendingClaimsResult) {
            this.FindPendingClaimsResult = FindPendingClaimsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastClaim", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLastClaimRequest {
        
        public GetLastClaimRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastClaimResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLastClaimResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BusinessEntities.Claim GetLastClaimResult;
        
        public GetLastClaimResponse() {
        }
        
        public GetLastClaimResponse(BusinessEntities.Claim GetLastClaimResult) {
            this.GetLastClaimResult = GetLastClaimResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClaim", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClaimRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int claimId;
        
        public GetClaimRequest() {
        }
        
        public GetClaimRequest(int claimId) {
            this.claimId = claimId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClaimResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClaimResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BusinessEntities.Claim GetClaimResult;
        
        public GetClaimResponse() {
        }
        
        public GetClaimResponse(BusinessEntities.Claim GetClaimResult) {
            this.GetClaimResult = GetClaimResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BusinessEntities.Claim claim;
        
        public SaveRequest() {
        }
        
        public SaveRequest(BusinessEntities.Claim claim) {
            this.claim = claim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SaveResult;
        
        public SaveResponse() {
        }
        
        public SaveResponse(string SaveResult) {
            this.SaveResult = SaveResult;
        }
    }
}
