<?xml version="1.0" encoding="utf-8"?><Database Name="BeginWF40_Persistence_Chap11" Class="LeadDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;Initial Catalog=BeginWF40_Persistence_Chap11;Integrated Security=True" SettingsObjectName="LeadGenerator.Properties.Settings" SettingsPropertyName="BeginWF40_Persistence_Chap11ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TrackActivity" Member="TrackActivities">
    <Type Name="TrackActivity">
      <Column Name="TrackActivityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkflowID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ActivityName" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Variables" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrackBookmark" Member="TrackBookmarks">
    <Type Name="TrackBookmark">
      <Column Name="TrackBookmarkID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkflowID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BookmarkName" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TrackCustom" Member="TrackCustoms">
    <Type Name="TrackCustom">
      <Column Name="TrackCustomID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkflowID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CustomEventName" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserData" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrackInstance" Member="TrackInstances">
    <Type Name="TrackInstance">
      <Column Name="TrackInstanceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkflowID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Lead" Member="Leads">
    <Type Name="Lead">
      <Column Name="LeadID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkflowID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPhone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Interests" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AssignedTo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Assignment" Member="Assignments">
    <Type Name="Assignment">
      <Column Name="AssignmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkflowID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LeadID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignedTo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateAssigned" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DateDue" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCompleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Lead_Assignment" Member="Lead" ThisKey="LeadID" OtherKey="LeadID" Type="Lead" IsForeignKey="true" />
    </Type>
  </Table>
</Database>